
export { default as Home } from './Home'
export { default as Error } from './Error'
export { default as AdminHome } from './admin/AdminHome'
export { default as ManageAgents } from './admin/ManageAgents'
export { default as ManageProperties } from './admin/ManageProperties'
export { default as AdminLogs } from './admin/AdminLogs'
export { default as ManageBlogs } from './admin/ManageBlogs'
export { default as ManageAmenities } from './admin/ManageAmenities'
export { default as ManageOffPlanProjects } from './admin/ManageOffPlanProjects'
export { default as ManageSubscribers } from './admin/ManageSubscribers'
export { default as ManageDubaiDevelopers } from './admin/ManageDubaiDevelopers'
export { default as PageAboutUs } from './admin/PageAboutUs'
export { default as PageDubaiFactNumbers } from './admin/PageDubaiFactNumbers'
export { default as PagePrivacyPolicy } from './admin/PagePrivacyPolicy'
export { default as PageGuideOnRenting } from './admin/PageGuideOnRenting'
export { default as PageGuideToSelling } from './admin/PageGuideToSelling'
export { default as PageInvestDubaiRealEstate } from './admin/PageInvestDubaiRealEstate'
export { default as PageWhyDubaI } from './admin/PageWhyDubai'
export { default as PageWhyInvestInOffPlan } from './admin/PageWhyInvestInOffPlan'
export { default as Settings } from './admin/Settings'
export {default as CreateAmenity} from './admin/CreateAmenity'
export {default as UpdateAmenity} from './admin/UpdateAmenity'
export {default as CreateDubaiDeveloper} from './admin/CreateDubaiDeveloper'
export { default as UpdateDubaiDeveloper } from './admin/UpdateDubaiDeveloper'
export { default as ManageDubaiAreas } from './admin/ManageDubaiAreas'
export { default as CreateDubaiArea } from './admin/CreateDubaiArea'
export { default as UpdateDubaiArea } from './admin/UpdateDubaiArea'
export { default as UpdateAgent } from './admin/UpdateAgent'
export { default as CreateAgent } from './admin/CreateAgent'
export { default as DetailsAgent } from './admin/DetailsAgent'
export { default as CreateSubscriber } from './admin/CreateSubscriber'
export { default as UpdateSubscriber } from './admin/UpdateSubscriber'
export { default as CreateBlog } from './admin/CreateBlog'
export { default as UpdateBlog } from './admin/UpdateBlog'
export { default as AdminLogin } from './admin/AdminLogin'
export { default as UpdateProperty } from './admin/UpdateProperty'
export { default as CreateProperty } from './admin/CreateProperty'
